import { useState, useEffect } from 'react'
import { gql, useMutation } from '@apollo/client'
import { Form, Input, SubmitButton } from '@/components/form'
import { totpSchema } from '@/lib/validate'
import Qr from '@/components/qr'
import CopyInput from '@/components/copy-input'
import CopyChip from '@/components/copy-chip'
import Alert from 'react-bootstrap/Alert'
import Button from 'react-bootstrap/Button'
import PageLoading from '@/components/page-loading'
import { useToast } from '@/components/toast'
import Clipboard from '@/svgs/clipboard-line.svg'

export const GENERATE_TOTP_SECRET = gql`
  mutation generateTotpSecret {
    generateTotpSecret {
      secret
      otpauthUrl
    }
  }
`

export const ENABLE_TOTP = gql`
  mutation enableTotp($secret: String!, $token: String!) {
    enableTotp(secret: $secret, token: $token) {
      recoveryCodes
    }
  }
`

export const DISABLE_TOTP = gql`
  mutation disableTotp($token: String!) {
    disableTotp(token: $token)
  }
`

export function TotpSetupModal ({ onClose, onSuccess }) {
  const toaster = useToast()
  const [generateSecret, { data, loading, error }] = useMutation(GENERATE_TOTP_SECRET)
  const [enableTotp] = useMutation(ENABLE_TOTP)
  const [recoveryCodes, setRecoveryCodes] = useState(null)
  const [submitError, setSubmitError] = useState(null)

  useEffect(() => {
    generateSecret().catch(err => {
      console.error(err)
      toaster.danger('Failed to generate 2FA secret')
    })
  }, [])

  if (loading || !data?.generateTotpSecret) {
    return <PageLoading />
  }

  if (error) {
    return <Alert variant='danger'>Failed to load 2FA setup. Please try again.</Alert>
  }

  const { secret, otpauthUrl } = data.generateTotpSecret

  if (recoveryCodes) {
    const codesText = recoveryCodes.join('\n')

    return (
      <div className='text-start'>
        <h4 className='text-success mb-3'>Two-Factor Authentication Enabled!</h4>
        <Alert variant='warning'>
          <strong className='d-block mb-1'>Important: Save Your Recovery Codes</strong>
          If you lose access to your authenticator app, these recovery codes are the <strong>only way</strong> to access your account. Each code can only be used once.
        </Alert>

        <div className='p-3 bg-light rounded text-monospace mb-3 border' style={{ fontFamily: 'monospace', whiteSpace: 'pre-wrap' }}>
          {recoveryCodes.map((code, idx) => (
            <div key={idx} className='py-1 fw-bold'>{code}</div>
          ))}
        </div>

        <div className='mb-3'>
          <CopyChip value={codesText} label='Copy all recovery codes' prefix={<Clipboard height={16} width={16} />} />
        </div>

        <Button
          variant='primary'
          className='w-100 mt-2'
          onClick={() => {
            if (onSuccess) onSuccess()
            if (onClose) onClose()
          }}
        >
          I have saved my recovery codes
        </Button>
      </div>
    )
  }

  return (
    <div className='text-start'>
      <h4 className='mb-3'>Set Up Two-Factor Authentication (2FA)</h4>
      <p className='text-muted small mb-3'>
        1. Scan this QR code with your authenticator app (such as Aegis, Google Authenticator, 1Password, or Bitwarden).
      </p>

      <div className='my-3 text-center'>
        <Qr value={otpauthUrl} copy={false} />
      </div>

      <div className='mb-3'>
        <label className='form-label text-muted small fw-bold mb-1'>Manual Entry Secret</label>
        <CopyInput value={secret} readOnly />
      </div>

      <p className='text-muted small mb-2'>
        2. Enter the 6-digit code generated by your app below to complete setup:
      </p>

      {submitError && (
        <Alert variant='danger' onClose={() => setSubmitError(null)} dismissible>
          {submitError}
        </Alert>
      )}

      <Form
        initial={{ token: '' }}
        schema={totpSchema}
        onSubmit={async ({ token }) => {
          setSubmitError(null)
          try {
            const res = await enableTotp({ variables: { secret, token } })
            if (res.data?.enableTotp?.recoveryCodes) {
              setRecoveryCodes(res.data.enableTotp.recoveryCodes)
              toaster.success('2FA enabled successfully')
            }
          } catch (err) {
            console.error(err)
            setSubmitError(err.message || 'Invalid 2FA code')
          }
        }}
      >
        <Input
          name='token'
          placeholder='123456'
          autoFocus
          required
        />
        <div className='d-flex justify-content-end mt-3'>
          <Button variant='secondary' className='me-2' onClick={onClose}>
            Cancel
          </Button>
          <SubmitButton variant='primary'>Enable 2FA</SubmitButton>
        </div>
      </Form>
    </div>
  )
}

export function TotpDisableModal ({ onClose, onSuccess }) {
  const toaster = useToast()
  const [disableTotp] = useMutation(DISABLE_TOTP)
  const [submitError, setSubmitError] = useState(null)

  return (
    <div className='text-start'>
      <h4 className='mb-3'>Disable Two-Factor Authentication (2FA)</h4>
      <p className='text-muted small mb-3'>
        To disable 2FA, enter a 6-digit code from your authenticator app or one of your recovery codes.
      </p>

      {submitError && (
        <Alert variant='danger' onClose={() => setSubmitError(null)} dismissible>
          {submitError}
        </Alert>
      )}

      <Form
        initial={{ token: '' }}
        schema={totpSchema}
        onSubmit={async ({ token }) => {
          setSubmitError(null)
          try {
            await disableTotp({ variables: { token } })
            toaster.success('2FA disabled')
            if (onSuccess) onSuccess()
            if (onClose) onClose()
          } catch (err) {
            console.error(err)
            setSubmitError(err.message || 'Invalid code')
          }
        }}
      >
        <Input
          name='token'
          placeholder='6-digit code or recovery code'
          autoFocus
          required
        />
        <div className='d-flex justify-content-end mt-3'>
          <Button variant='secondary' className='me-2' onClick={onClose}>
            Cancel
          </Button>
          <SubmitButton variant='danger'>Disable 2FA</SubmitButton>
        </div>
      </Form>
    </div>
  )
}
